/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Color = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface Command { 'direction' : Direction, 'color' : Color }
export type Density = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Detection {
  'direction' : Direction,
  'cameraCount' : bigint,
  'densityPercentage' : bigint,
  'noiseDbLevel' : bigint,
}
export type Direction = { 'east' : null } |
  { 'west' : null } |
  { 'north' : null };
export interface Emergency {
  'id' : bigint,
  'direction' : Direction,
  'active' : boolean,
  'timestamp' : bigint,
  'vehicleId' : string,
}
export interface Signal {
  'density' : Density,
  'color' : Color,
  'countdown' : bigint,
  'vehicleCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Violation {
  'id' : bigint,
  'status' : string,
  'direction' : Direction,
  'timestamp' : bigint,
  'severity' : string,
  'plate' : string,
  'violationType' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addViolation' : ActorMethod<[Direction, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearEmergency' : ActorMethod<[bigint], undefined>,
  'completePendingCommand' : ActorMethod<[Command], undefined>,
  'getAdapterData' : ActorMethod<[], Array<[Direction, Signal]>>,
  'getArduinoData' : ActorMethod<[], Array<[Direction, Signal]>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmergencyState' : ActorMethod<[], Array<[bigint, Emergency]>>,
  'getPendingCommands' : ActorMethod<[], Array<Command>>,
  'getReport' : ActorMethod<[], Array<[Direction, Signal]>>,
  'getSignalState' : ActorMethod<[], [Array<[Direction, Signal]>, bigint]>,
  'getStatistics' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint]
  >,
  'getStatusAsync' : ActorMethod<
    [],
    [
      Array<[Direction, Signal]>,
      Array<[bigint, Emergency]>,
      Array<[bigint, Violation]>,
      bigint,
    ]
  >,
  'getViolationState' : ActorMethod<[], Array<[bigint, Violation]>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmergencyActive' : ActorMethod<[Direction], boolean>,
  'isTrafficDirectionRed' : ActorMethod<[Direction], boolean>,
  'nextCycle' : ActorMethod<[], [Direction, Color]>,
  'toggleRedLight' : ActorMethod<[], undefined>,
  'triggerEmergency' : ActorMethod<[Direction, string], undefined>,
  'updateSensorData' : ActorMethod<[Direction, bigint, Density], Detection>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];