/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Direction = IDL.Variant({
  'east' : IDL.Null,
  'west' : IDL.Null,
  'north' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Color = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const Command = IDL.Record({ 'direction' : Direction, 'color' : Color });
export const Density = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Signal = IDL.Record({
  'density' : Density,
  'color' : Color,
  'countdown' : IDL.Nat,
  'vehicleCount' : IDL.Nat,
});
export const Emergency = IDL.Record({
  'id' : IDL.Nat,
  'direction' : Direction,
  'active' : IDL.Bool,
  'timestamp' : IDL.Int,
  'vehicleId' : IDL.Text,
});
export const Violation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'direction' : Direction,
  'timestamp' : IDL.Int,
  'severity' : IDL.Text,
  'plate' : IDL.Text,
  'violationType' : IDL.Text,
});
export const Detection = IDL.Record({
  'direction' : Direction,
  'cameraCount' : IDL.Nat,
  'densityPercentage' : IDL.Nat,
  'noiseDbLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addViolation' : IDL.Func(
      [Direction, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearEmergency' : IDL.Func([IDL.Nat], [], []),
  'completePendingCommand' : IDL.Func([Command], [], []),
  'getAdapterData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Direction, Signal))],
      ['query'],
    ),
  'getArduinoData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Direction, Signal))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmergencyState' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Emergency))],
      ['query'],
    ),
  'getPendingCommands' : IDL.Func([], [IDL.Vec(Command)], ['query']),
  'getReport' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Direction, Signal))],
      ['query'],
    ),
  'getSignalState' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Direction, Signal)), IDL.Nat],
      ['query'],
    ),
  'getStatistics' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getStatusAsync' : IDL.Func(
      [],
      [
        IDL.Vec(IDL.Tuple(Direction, Signal)),
        IDL.Vec(IDL.Tuple(IDL.Nat, Emergency)),
        IDL.Vec(IDL.Tuple(IDL.Nat, Violation)),
        IDL.Int,
      ],
      [],
    ),
  'getViolationState' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Violation))],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmergencyActive' : IDL.Func([Direction], [IDL.Bool], []),
  'isTrafficDirectionRed' : IDL.Func([Direction], [IDL.Bool], []),
  'nextCycle' : IDL.Func([], [Direction, Color], []),
  'toggleRedLight' : IDL.Func([], [], []),
  'triggerEmergency' : IDL.Func([Direction, IDL.Text], [], []),
  'updateSensorData' : IDL.Func([Direction, IDL.Nat, Density], [Detection], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Direction = IDL.Variant({
    'east' : IDL.Null,
    'west' : IDL.Null,
    'north' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Color = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const Command = IDL.Record({ 'direction' : Direction, 'color' : Color });
  const Density = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Signal = IDL.Record({
    'density' : Density,
    'color' : Color,
    'countdown' : IDL.Nat,
    'vehicleCount' : IDL.Nat,
  });
  const Emergency = IDL.Record({
    'id' : IDL.Nat,
    'direction' : Direction,
    'active' : IDL.Bool,
    'timestamp' : IDL.Int,
    'vehicleId' : IDL.Text,
  });
  const Violation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'direction' : Direction,
    'timestamp' : IDL.Int,
    'severity' : IDL.Text,
    'plate' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const Detection = IDL.Record({
    'direction' : Direction,
    'cameraCount' : IDL.Nat,
    'densityPercentage' : IDL.Nat,
    'noiseDbLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addViolation' : IDL.Func(
        [Direction, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearEmergency' : IDL.Func([IDL.Nat], [], []),
    'completePendingCommand' : IDL.Func([Command], [], []),
    'getAdapterData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Direction, Signal))],
        ['query'],
      ),
    'getArduinoData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Direction, Signal))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmergencyState' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Emergency))],
        ['query'],
      ),
    'getPendingCommands' : IDL.Func([], [IDL.Vec(Command)], ['query']),
    'getReport' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Direction, Signal))],
        ['query'],
      ),
    'getSignalState' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Direction, Signal)), IDL.Nat],
        ['query'],
      ),
    'getStatistics' : IDL.Func(
        [],
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        ['query'],
      ),
    'getStatusAsync' : IDL.Func(
        [],
        [
          IDL.Vec(IDL.Tuple(Direction, Signal)),
          IDL.Vec(IDL.Tuple(IDL.Nat, Emergency)),
          IDL.Vec(IDL.Tuple(IDL.Nat, Violation)),
          IDL.Int,
        ],
        [],
      ),
    'getViolationState' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Violation))],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmergencyActive' : IDL.Func([Direction], [IDL.Bool], []),
    'isTrafficDirectionRed' : IDL.Func([Direction], [IDL.Bool], []),
    'nextCycle' : IDL.Func([], [Direction, Color], []),
    'toggleRedLight' : IDL.Func([], [], []),
    'triggerEmergency' : IDL.Func([Direction, IDL.Text], [], []),
    'updateSensorData' : IDL.Func(
        [Direction, IDL.Nat, Density],
        [Detection],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };