/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    density: Density;
    color: Color;
    countdown: bigint;
    vehicleCount: bigint;
}
export interface Detection {
    direction: Direction;
    cameraCount: bigint;
    densityPercentage: bigint;
    noiseDbLevel: bigint;
}
export interface Violation {
    id: bigint;
    status: string;
    direction: Direction;
    timestamp: bigint;
    severity: string;
    plate: string;
    violationType: string;
}
export interface Emergency {
    id: bigint;
    direction: Direction;
    active: boolean;
    timestamp: bigint;
    vehicleId: string;
}
export interface Command {
    direction: Direction;
    color: Color;
}
export enum Color {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum Density {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Direction {
    east = "east",
    west = "west",
    north = "north"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addViolation(direction: Direction, plate: string, violationType: string, severity: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearEmergency(id: bigint): Promise<void>;
    completePendingCommand(command: Command): Promise<void>;
    getAdapterData(): Promise<Array<[Direction, Signal]>>;
    getArduinoData(): Promise<Array<[Direction, Signal]>>;
    getCallerUserRole(): Promise<UserRole>;
    getEmergencyState(): Promise<Array<[bigint, Emergency]>>;
    getPendingCommands(): Promise<Array<Command>>;
    getReport(): Promise<Array<[Direction, Signal]>>;
    getSignalState(): Promise<[Array<[Direction, Signal]>, bigint]>;
    getStatistics(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint]>;
    getStatusAsync(): Promise<[Array<[Direction, Signal]>, Array<[bigint, Emergency]>, Array<[bigint, Violation]>, bigint]>;
    getViolationState(): Promise<Array<[bigint, Violation]>>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isEmergencyActive(direction: Direction): Promise<boolean>;
    isTrafficDirectionRed(direction: Direction): Promise<boolean>;
    nextCycle(): Promise<[Direction, Color]>;
    toggleRedLight(): Promise<void>;
    triggerEmergency(direction: Direction, vehicleId: string): Promise<void>;
    updateSensorData(direction: Direction, vehicleCount: bigint, density: Density): Promise<Detection>;
}
import type { Color as _Color, Command as _Command, Density as _Density, Detection as _Detection, Direction as _Direction, Emergency as _Emergency, Signal as _Signal, UserRole as _UserRole, Violation as _Violation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addViolation(arg0: Direction, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addViolation(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addViolation(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearEmergency(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearEmergency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearEmergency(arg0);
            return result;
        }
    }
    async completePendingCommand(arg0: Command): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completePendingCommand(to_candid_Command_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePendingCommand(to_candid_Command_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAdapterData(): Promise<Array<[Direction, Signal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdapterData();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdapterData();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArduinoData(): Promise<Array<[Direction, Signal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArduinoData();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArduinoData();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyState(): Promise<Array<[bigint, Emergency]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyState();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyState();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingCommands(): Promise<Array<Command>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCommands();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCommands();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(): Promise<Array<[Direction, Signal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalState(): Promise<[Array<[Direction, Signal]>, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalState();
                return [
                    from_candid_vec_n9(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalState();
            return [
                from_candid_vec_n9(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async getStatistics(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4],
                    result[5],
                    result[6],
                    result[7]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4],
                result[5],
                result[6],
                result[7]
            ];
        }
    }
    async getStatusAsync(): Promise<[Array<[Direction, Signal]>, Array<[bigint, Emergency]>, Array<[bigint, Violation]>, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatusAsync();
                return [
                    from_candid_vec_n9(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n21(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_vec_n28(this._uploadFile, this._downloadFile, result[2]),
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatusAsync();
            return [
                from_candid_vec_n9(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n21(this._uploadFile, this._downloadFile, result[1]),
                from_candid_vec_n28(this._uploadFile, this._downloadFile, result[2]),
                result[3]
            ];
        }
    }
    async getViolationState(): Promise<Array<[bigint, Violation]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getViolationState();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getViolationState();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEmergencyActive(arg0: Direction): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEmergencyActive(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEmergencyActive(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isTrafficDirectionRed(arg0: Direction): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTrafficDirectionRed(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTrafficDirectionRed(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async nextCycle(): Promise<[Direction, Color]> {
        if (this.processError) {
            try {
                const result = await this.actor.nextCycle();
                return [
                    from_candid_Direction_n11(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_Color_n17(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nextCycle();
            return [
                from_candid_Direction_n11(this._uploadFile, this._downloadFile, result[0]),
                from_candid_Color_n17(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async toggleRedLight(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleRedLight();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleRedLight();
            return result;
        }
    }
    async triggerEmergency(arg0: Direction, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerEmergency(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerEmergency(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async updateSensorData(arg0: Direction, arg1: bigint, arg2: Density): Promise<Detection> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensorData(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Density_n32(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Detection_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensorData(to_candid_Direction_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Density_n32(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Detection_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Color_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Color): Color {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Command_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Command): Command {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Density_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Density): Density {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Detection_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Detection): Detection {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Emergency_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Emergency): Emergency {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Violation_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Violation): Violation {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    density: _Density;
    color: _Color;
    countdown: bigint;
    vehicleCount: bigint;
}): {
    density: Density;
    color: Color;
    countdown: bigint;
    vehicleCount: bigint;
} {
    return {
        density: from_candid_Density_n15(_uploadFile, _downloadFile, value.density),
        color: from_candid_Color_n17(_uploadFile, _downloadFile, value.color),
        countdown: value.countdown,
        vehicleCount: value.vehicleCount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    direction: _Direction;
    active: boolean;
    timestamp: bigint;
    vehicleId: string;
}): {
    id: bigint;
    direction: Direction;
    active: boolean;
    timestamp: bigint;
    vehicleId: string;
} {
    return {
        id: value.id,
        direction: from_candid_Direction_n11(_uploadFile, _downloadFile, value.direction),
        active: value.active,
        timestamp: value.timestamp,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
    color: _Color;
}): {
    direction: Direction;
    color: Color;
} {
    return {
        direction: from_candid_Direction_n11(_uploadFile, _downloadFile, value.direction),
        color: from_candid_Color_n17(_uploadFile, _downloadFile, value.color)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    direction: _Direction;
    timestamp: bigint;
    severity: string;
    plate: string;
    violationType: string;
}): {
    id: bigint;
    status: string;
    direction: Direction;
    timestamp: bigint;
    severity: string;
    plate: string;
    violationType: string;
} {
    return {
        id: value.id,
        status: value.status,
        direction: from_candid_Direction_n11(_uploadFile, _downloadFile, value.direction),
        timestamp: value.timestamp,
        severity: value.severity,
        plate: value.plate,
        violationType: value.violationType
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
    cameraCount: bigint;
    densityPercentage: bigint;
    noiseDbLevel: bigint;
}): {
    direction: Direction;
    cameraCount: bigint;
    densityPercentage: bigint;
    noiseDbLevel: bigint;
} {
    return {
        direction: from_candid_Direction_n11(_uploadFile, _downloadFile, value.direction),
        cameraCount: value.cameraCount,
        densityPercentage: value.densityPercentage,
        noiseDbLevel: value.noiseDbLevel
    };
}
function from_candid_tuple_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Direction, _Signal]): [Direction, Signal] {
    return [
        from_candid_Direction_n11(_uploadFile, _downloadFile, value[0]),
        from_candid_Signal_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Emergency]): [bigint, Emergency] {
    return [
        value[0],
        from_candid_Emergency_n23(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Violation]): [bigint, Violation] {
    return [
        value[0],
        from_candid_Violation_n30(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    east: null;
} | {
    west: null;
} | {
    north: null;
}): Direction {
    return "east" in value ? Direction.east : "west" in value ? Direction.west : "north" in value ? Direction.north : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Density {
    return "low" in value ? Density.low : "high" in value ? Density.high : "medium" in value ? Density.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): Color {
    return "red" in value ? Color.red : "green" in value ? Color.green : "yellow" in value ? Color.yellow : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Emergency]>): Array<[bigint, Emergency]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Command>): Array<Command> {
    return value.map((x)=>from_candid_Command_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Violation]>): Array<[bigint, Violation]> {
    return value.map((x)=>from_candid_tuple_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Direction, _Signal]>): Array<[Direction, Signal]> {
    return value.map((x)=>from_candid_tuple_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Color_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): _Color {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Command_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Command): _Command {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Density_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Density): _Density {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: Direction;
    color: Color;
}): {
    direction: _Direction;
    color: _Color;
} {
    return {
        direction: to_candid_Direction_n1(_uploadFile, _downloadFile, value.direction),
        color: to_candid_Color_n7(_uploadFile, _downloadFile, value.color)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    east: null;
} | {
    west: null;
} | {
    north: null;
} {
    return value == Direction.east ? {
        east: null
    } : value == Direction.west ? {
        west: null
    } : value == Direction.north ? {
        north: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Density): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Density.low ? {
        low: null
    } : value == Density.high ? {
        high: null
    } : value == Density.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == Color.red ? {
        red: null
    } : value == Color.green ? {
        green: null
    } : value == Color.yellow ? {
        yellow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
